services:
  - type: web
    name: portfolio-builder
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 30m
      - key: SMTP_HOST
        scope: project
      - key: SMTP_PORT
        scope: project
      - key: SMTP_USER
        scope: project
      - key: SMTP_PASS
        scope: project
      - key: BREVO_API_KEY
        scope: project
      - key: BREVO_SENDER_EMAIL
        scope: project
      - key: FRONTEND_URL
        scope: project
