services:
  - type: web
    name: portfolio-builder
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://portfolio_builder_bdd_user:2ttYsFLs3KHY3WApN20ZOVPF7AdSH7LT@dpg-d5mfmin5r7bs73d4dl2g-a/portfolio_builder_bdd
      - key: JWT_SECRET
        value: super_secret_jwt_key_change_in_production_2026
      - key: JWT_EXPIRES_IN
        value: 30m
      - key: SMTP_HOST
        scope: project
      - key: SMTP_PORT
        scope: project
      - key: SMTP_USER
        scope: project
      - key: SMTP_PASS
        scope: project
      - key: BREVO_API_KEY
        scope: project
      - key: BREVO_SENDER_EMAIL
        scope: project
